employees_web/employees/urls.py
from django.urls import path, include
from rest_framework import routers
from django.contrib import admin
from . import views

router = routers.DefaultRouter()

router.register('Employees', views.EmployeesView)
app_name = 'employees'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(router.urls)),
    path('index/', views.index, name="index"),
    path('<slug:slug>/', views.employees_list, name="employees_list"),

]

employees_web/employees_web/urls.py
from django import views
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees_web/employees/models.py
from django.db import models


# Create your models here.
class Employees(models.Model):

    employees_id = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)
    salary = models.CharField(max_length=50)
    job_id = models.CharField(max_length=50)
    department_id = models.CharField(max_length=50)
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.thumb

employees_web/employees/views.py
from django.http import HttpResponse
from django.shortcuts import render
from rest_framework.renderers import BrowsableAPIRenderer, JSONRenderer
from .serializers import EmployeesSerializer
from .models import Employees
from rest_framework import viewsets


class EmployeesView(viewsets.ModelViewSet):
    queryset = Employees.objects.all()
    serializer_class = EmployeesSerializer

class CustomBrowsableAPIRenderer(BrowsableAPIRenderer):
    def get_default_renderer(self, view):
        return JSONRenderer()


def index(request):
    employees = Employees.objects.all().order_by('employees_id')
    return render(request, 'index.html', {'Employees': employees})


def employees_list(request, slug):
    employees = Employees.objects.get(slug=slug)
    return render(request, 'employees_list.html', {'Employees': employees})

employees_web/employees/templates/base_layout.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My website</title>
    <link rel="stylesheet" href="{% static 'mystyle.css'%}">
</head>

<body>
<div class="wrapper">

    {% block content %}

    {% endblock %}
</div>
</body>
</html>

employees_web/employees/templates/employees_list.html
{% extends 'base_layout.html' %}
{% block content %}

<div class="employees-list">
    <div class="Employee">

        <img src="{{Employee.thumb.url}} " align="middle"/>
        <h2>{{Employee.title }}</h2>
        <h3>{{Employee.body }}</h3>
        <h3>{{Employee.director }}</h3>
        <h3>{{Employee.cast }}</h3>
        <h3>{{Employee.release_date }}</h3>

    </div>
</div>
{% endblock %}

employees_web/employees/templates/index.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="index">
    {% for Employee in employees %}
    <div class="Employees">
        <a href="{% url 'employees:employees_list' slug=Employees.slug %}"><img src="{{Employees.thumb.url}}"/></a>
        <h2><a href="{% url 'employees:employees_list' slug=Employee.slug %}"></a> </h2>

    </div>
    {% endfor %}
</div>
{% endblock %}